---

### instantiate a vPSA client

- name: get Snort Docker image
  docker_image:
    name: ubuntu:latest

- name: start Ubuntu Xenial container
  docker_container:
    name: vpsa-client
    image: ubuntu
    #env:
    state: started
    network_mode: bridge
    networks:
      - name: "{{ vlmgmt }}"
        aliases:
          - son-mgmt
      - name: "{{ vlenduser }}"
        aliases:
          - vpsa-enduser
    restart_policy: "unless-stopped"

- debug:
    msg: "vPSA client up and running"

